import "./globals.css";
import { Inter } from "next/font/google";
import Navvar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Phuong - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navvar/>
        {children}
      </body>
    </html>
  );
}
